### ISSUE TITLE
Worker nodes initially is only 1

### ISSUE THREAD

**Issue by cleyson1102** [maksim-paskal/hcloud-k8s-ctl#71]
Hello greetings, thanks in advance for the collaboration of the repository.

I have a question, I'm trying to build a cluster that has 3 worker nodes at the time it starts, but no matter how much I change the values ​​in the configuration file, it only builds 1 worker, what would be the correct configuration to achieve what I'm looking for? I share my config.yaml

clusterName: 
kubeConfigPath: ~/.kube/hcloud
hetznerToken:
  main: 
sshPrivateKey: ~/.ssh/cluster_rsa
sshPublicKey: ~/.ssh/cluster_rsa.pub
ipRange: "10.0.0.0/16"
masterCount: 3
networkZone: us-east
location: ash
datacenter: ash-dc1
masterServers:
  namepattern: master-%d
  servertype: cpx21
  image: ubuntu-20.04
  labels:
    role: master
masterLoadBalancer:
    loadbalancertype: lb11
    listenport: 6443
    destinationport: 6443
autoscaler:
  enabled: true
  args:
    - --v=4
    - --cloud-provider=hetzner
    - --stderrthreshold=info
    - --expander=least-waste
    - --scale-down-enabled=true
    - --skip-nodes-with-local-storage=false
    - --skip-nodes-with-system-pods=false
    - --scale-down-utilization-threshold=0.8
  workers:
    - location: ash
      min: 3
      max: 20
      type:
        - cpx31

**Comment by maksim-paskal** [comment]
@cleyson1102 thanks for raising this issue

It's not an error, autoscaling component that runs in cluster doesn't initialy raise number of nodes that below minimal value, your cluster will automaticaly autoscale number of nodes if cluster will have `Pending` pod.

Your issue was raised in autoscaling component https://github.com/kubernetes/autoscaler/pull/5195 that was fixed now only for latest version of kubernetes v1.26 more details https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#my-cluster-is-below-minimum--above-maximum-number-of-nodes-but-ca-did-not-fix-that-why

It will be fixed later for kubernetes v1.26
